#!/bin/sh
set -e
# Install Node-RED using the official installer (installs Node.js too)
# See: https://nodered.org/docs/getting-started/raspberrypi
echo "Running official Node-RED installer..."
bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)

# Enable and start the service
sudo systemctl enable nodered.service
sudo systemctl start nodered.service

echo "Node-RED installed. Access at http://localhost:1880"
